steps:
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'multiplescrapers', '--trigger-topic=update-db', '--runtime=python38', '--entry-point=hello_pubsub']
    dir: 'https://source.developers.google.com/projects/scrapingnlp/repos/github_hack-learning_datascience-scrapers/moveable-aliases/main'
